#! /bin/sh -

set -e

if [ "$(id -u)" -ne "0" ]
then
  exec sudo "$0" "$@"
fi

case "$1" in
  i*)
  ip netns delete xdp-test 2> /dev/null || true
  ip netns add xdp-test
  ip link delete veth0 2> /dev/null || true
  ip link add veth0 type veth peer veth1 netns xdp-test
  ip address add 192.168.0.1/30 dev veth0
  ip link set veth0 up
  ip netns exec xdp-test ip address add 192.168.0.2/30 dev veth1
  ip netns exec xdp-test ip link set veth1 up
  ip netns exec xdp-test ip route replace default via 192.168.0.1
  nft delete table xdp-test 2> /dev/null || true
  nft add table xdp-test
  nft add chain xdp-test prerouting '{ type nat hook prerouting priority dstnat; }'
  nft add rule xdp-test prerouting iif veth0 ip protocol udp udp dport 53 counter dnat to 8.8.8.8
  nft add chain xdp-test postrouting '{ type nat hook postrouting priority srcnat; }'
  nft add rule xdp-test postrouting iif veth0 counter masquerade
  echo 1 > /proc/sys/net/ipv4/ip_forward
  ;;
  off)
  ip link set veth0 xdp off
  ;;
  on)
  ip link set veth0 xdp object xdp_main
  ;;
  q*)
  ip netns exec xdp-test nslookup -timeout=1 -type=A dns.google 192.168.0.1
  ;;
esac
